title = "Brainy Day Ideas"
baseURL = "http://www.brainydayideas.com"
languageCode = "en-us"
theme = "ananke"



MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-126130234-1"
enableRobotsTXT = true
disqusShortname = "brainydayideas"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
 
[blackfriday]
  hrefTargetBlank = true 


[params]
  favicon = "/images/favicon.png"
  description = "Fun and enagaging ideas (rain or shine)."
  env = "production"
  facebook = ""
  twitter = "https://twitter.com/brainydayideas"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/pinkboots.png"
  recent_posts_number = 2

  [permalinks]
    post = "/:year/:month/:title/"
